Add Linux Updater Support
LITdevs/SaladBind pull request #129
Opened 2021-12-05 05:14 UTC by Craftzman7

All this does is allow the updater to download the new binary version on Linux, currently all it does is... nothing (pretty eventful I know).

2021-12-05 09:26 UTC, Vukkyy commented
Ha! We actually recently disabled the updater on Linux due to SaladBind being available on the AUR - we thought it'd be funny to have a package manager to do, you know, these kinds of things, just for the software to go "update me pl0x!!"

That being said, your patch looks pretty good to me - we could probably implement this, just have to hack in a way to not make package manager installations throw the update message.

2021-12-05 16:53 UTC, Craftzman7 commented
> Ha! We actually recently disabled ([19807e4](https://github.com/LITdevs/SaladBind/commit/19807e4b575e95c65f301ee9abb6a9e1f93b4078)) the updater on Linux due to SaladBind being available on the AUR - we thought it'd be funny to have a package manager to do, you know, these kinds of things, just for the software to go "update me pl0x!!"
> 
> That being said, your patch looks pretty good to me - we could probably implement this, just have to hack in a way to not make package manager installations throw the update message.

This was more geared toward people running something other than Arch. I could probably check if they are on Arch and just do what the old updater did and also say it's available in the AUR.

2021-12-05 16:55 UTC, vtheskeleton commented
I think that would be the best option

2021-12-05 17:03 UTC, Craftzman7 commented
Okay it wasn't as hard as I thought it would be.

2021-12-05 17:06 UTC, vtheskeleton requested changes

2021-12-05 17:06 UTC, vtheskeleton commented on src/update.js
> +		setTimeout(function() { process.exit(0) }, 10000);
You should probably prevent it from continuing forward if on arch

2021-12-05 17:07 UTC, Craftzman7 commented on src/update.js
> +		setTimeout(function() { process.exit(0) }, 10000);
`process.exit` is called. Is that not enough?

2021-12-05 17:10 UTC, vtheskeleton commented on src/update.js
> +		setTimeout(function() { process.exit(0) }, 10000);
well you call process.exit after 10 seconds

2021-12-05 17:11 UTC, Craftzman7 commented on src/update.js
> +		setTimeout(function() { process.exit(0) }, 10000);
Oh I see what you mean.

2021-12-05 17:12 UTC, Craftzman7 commented on src/update.js
> +		setTimeout(function() { process.exit(0) }, 10000);
I put that there so the user can read it lol.

2021-12-05 17:14 UTC, TheBlueBurger commented on src/update.js
> +		setTimeout(function() { process.exit(0) }, 10000);
The code will continue running because you didnt do a return i think

2021-12-06 10:57 UTC, Vukkyy commented on src/update.js
> +		spinner.succeed(chalk.bold.yellow(`Arch Linux has a SaladBind package available in the AUR\n If you happen to be using that already please contact your nearest package manager/AUR helper to update
Ok, but how would I go about not running the updater if the AUR package has been installed?

2021-12-06 16:10 UTC, Username404-59 commented on src/update.js
> +		spinner.succeed(chalk.bold.yellow(`Arch Linux has a SaladBind package available in the AUR\n If you happen to be using that already please contact your nearest package manager/AUR helper to update
Why not just define a variable at build time to prohibit updates when making the AUR package?

2021-12-06 18:15 UTC, Craftzman7 commented on src/update.js
> +		spinner.succeed(chalk.bold.yellow(`Arch Linux has a SaladBind package available in the AUR\n If you happen to be using that already please contact your nearest package manager/AUR helper to update
If you want I could have it check if the AUR package is installed, if it isn't just display a warning and update anyway. If it is installed I could have them consult the AUR helper or package manager.

2021-12-06 18:32 UTC, Craftzman7 commented on src/update.js
> +		spinner.succeed(chalk.bold.yellow(`Arch Linux has a SaladBind package available in the AUR\n If you happen to be using that already please contact your nearest package manager/AUR helper to update
Resolved with latest commit

2021-12-06 18:32 UTC, TheBlueBurger commented
ill test this later (hopefully tomorrow)

2021-12-06 22:02 UTC, Craftzman7 commented
The window manager detection suffers from a number of bugs. I'll need to fix that first. I'll mark as ready when I'm done. (It's probably gonna be a couple days)

2021-12-07 05:00 UTC, Craftzman7 commented
KDE is confirmed to work

2021-12-08 21:53 UTC, Craftzman7 commented
Ok. Ready for review now.

2021-12-28 08:18 UTC, TheBlueBurger requested changes

2021-12-28 08:18 UTC, TheBlueBurger commented on src/update.js
> +						exec(`chmod +x ${path.join(saladbind_directory, filename)}`)
This can break if the path has spaces

2021-12-28 17:43 UTC, Craftzman7 commented on src/update.js
> +						exec(`chmod +x ${path.join(saladbind_directory, filename)}`)
Fixed

2022-04-21 05:29 UTC, closed without merging