Gminer support
LITdevs/SaladBind pull request #135
Opened 2021-12-15 08:19 UTC by memedmusic

Adds support for gminer because some person in the discord server asked for it. 

Since gminer is sussy i had to rearrange a few things

Gminer only supports stratum, so I had to make it change the ethproxy pools to stratum. Gminer also requires a separate port argument, so I had to do more sussy code to fix that

Tested to work on windows

2021-12-15 08:45 UTC, memedmusic commented
Also btw to get gminer to work users will need to update saladbind

2022-01-25 12:13 UTC, Vukkyy requested changes

2022-01-25 12:13 UTC, Vukkyy commented on internal/miners.json
> +        },  "GMiner": {
```suggestion
        },  
        "GMiner": {
```
absolutely horribly written would not ercommend

this is how you do it right

2022-01-25 22:23 UTC, actuallyasmartname requested changes

2022-01-25 22:23 UTC, actuallyasmartname commented on internal/miners.json
> +                "win32": "https://github.com/develsoftware/GMinerRelease/releases/download/2.74/gminer_2_74_windows64.zip",
```suggestion
                "win32": "https://github.com/develsoftware/GMinerRelease/releases/download/2.75/gminer_2_75_windows64.zip",
```
gminer updated

2022-01-26 21:52 UTC, actuallyasmartname requested changes

2022-01-26 21:52 UTC, actuallyasmartname commented on internal/miners.json
> +                "linux": "https://github.com/develsoftware/GMinerRelease/releases/download/2.74/gminer_2_74_linux64.tar.xz"
ops i forgot to comment on the linux version

2022-01-26 21:52 UTC, actuallyasmartname commented
also update the linux version, idk how i missed that

2022-04-21 05:29 UTC, closed without merging