Add Prohashing pool
LITdevs/SaladBind pull request #86
Opened 2021-09-24 10:56 UTC by vtheskeleton

lets begin with this:

![image](https://user-images.githubusercontent.com/47392011/134663588-2964b93b-5f01-4b64-9581-050038ccc3e5.png)

Github defaulted to sus sus amongus

next up: I added the Prohashing pool. This shouldn't be merged before we decide that the public beta was a success

2021-09-24 11:06 UTC, TheBlueBurger requested changes

2021-09-24 11:06 UTC, TheBlueBurger commented on src/setup.js
> +			console.log(chalk.bold.red("Could not find your id for Prohashing! You can use the Automatic (Auth Token) method or manual instead."));
Maybe tell the user it's possible to press override in salad and start mining a few minutes? That way would work right? Unable to test right now

2021-09-24 11:06 UTC, TheBlueBurger commented on src/setup.js
> +					}, 3500);
Why do you need to wait if the user has nothing to read while waiting?

2021-09-24 11:07 UTC, vtheskeleton commented on src/setup.js
> +			console.log(chalk.bold.red("Could not find your id for Prohashing! You can use the Automatic (Auth Token) method or manual instead."));
We cant confirm it will force it onto the new pool

2021-09-24 11:07 UTC, vtheskeleton commented on src/setup.js
> +					}, 3500);
because i copied your code

2021-10-04 09:27 UTC, TheBlueBurger commented
There seems to just be 2 issues until this can be merged, I can look into them if my pc fan decides to start working

2021-10-04 10:21 UTC, vtheskeleton commented
Which Issues?

2021-10-04 10:21 UTC, vtheskeleton commented
i forgor 💀

2021-10-05 12:27 UTC, merged